### ISSUE TITLE
change specification for Cloud RPC Client

### ISSUE THREAD

**Issue by tamarafischer** [eclipse-uprotocol/uprotocol-java#57]
Currently in the specifications here: https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/up-l2/rpcclient.adoc
It says:
"The UUri and UAttributes passed to invokeMethod() MUST be cached non-persistent memory per call, this is to be able to complete the Future when the response is received from the server."

This might be a problem for cloud implementations since the node that sends the rpc request, might not be the same node receiving the rpc response. It could be difficult or inefficient to implement the MUST be cached non-persistent memory per call.

We would need to solve this problem by using something like an Akka Cluster that distributes the in-memory calls or use a database to persist the information while the stateless nodes poll for the response.

**Comment by stevenhartley** [comment]
I'm fixing this on #53
